---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcap-claim
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeek-claim
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suricata-claim
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-claim
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runtime-logs-claim
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Gi  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-claim
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-backup-claim
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi  
