---
apiVersion: v1
data:
  FILEBEAT_CLEAN_INACTIVE: 180m
  FILEBEAT_CLEAN_REMOVED: "true"
  FILEBEAT_CLOSE_EOF: "true"
  FILEBEAT_CLOSE_INACTIVE: 120s
  FILEBEAT_CLOSE_INACTIVE_LIVE: 90m
  FILEBEAT_CLOSE_REMOVED: "true"
  FILEBEAT_CLOSE_RENAMED: "true"
  FILEBEAT_IGNORE_OLDER: 120m
  FILEBEAT_SCAN_FREQUENCY: 10s
  FILEBEAT_TCP_LISTEN: "true"
  FILEBEAT_TCP_LOG_FORMAT: json
  FILEBEAT_TCP_PARSE_DROP_FIELD: message
  FILEBEAT_TCP_PARSE_SOURCE_FIELD: message
  FILEBEAT_TCP_PARSE_TARGET_FIELD: miscbeat
  FILEBEAT_TCP_TAG: _malcolm_beats
  FILEBEAT_WATCHER_POLLING: "true"
  FILEBEAT_WATCHER_POLLING_ASSUME_CLOSED_SEC: "10"
kind: ConfigMap
metadata:
  name: filebeat-env

---
apiVersion: v1
kind: Service
metadata:
  name: filebeat
  
spec:
  # use "type: ClusterIP" if using Ingress-NGINX as illustrated in 99-ingress-nginx.yml.example
  # use "type: LoadBalancer" if using AWS Load Balancer as illustrated in 99-ingress-alb.yml.example
  type: ClusterIP
  ports:
    - port: 5045
      protocol: TCP
      name: tcpjson
  selector:
    name: filebeat-deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deployment
  
spec:
  selector:
    matchLabels:
      name: filebeat-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: filebeat-deployment
    spec:
      containers:
      - name: filebeat-container
        image: "{{ .Values.image.repository }}/filebeat-oss:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        ports:
          - name: tcpjson
            protocol: TCP
            containerPort: 5045
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: nginx-env
          - configMapRef:
              name: opensearch-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: beats-common-env
          - configMapRef:
              name: filebeat-env
        env:
          - name: PCAP_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        livenessProbe:
          exec:
            command:
            - supervisorctl
            - status
            - filebeat
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: filebeat-var-local-catrust-volume
          - mountPath: /var/local/curlrc/secretmap
            name: filebeat-opensearch-curlrc-secret-volume
          - mountPath: /certs/secretmap
            name: filebeat-certs-secret-volume
          - mountPath: "/zeek"
            name: filebeat-zeek-volume
          - mountPath: "/suricata"
            name: filebeat-suricata-volume
          - name: filebeat-nginx-runtime-logs-volume
            mountPath: /nginx
            subPath: "nginx"
      initContainers:
      - name: filebeat-dirinit-container
        image: "{{ .Values.image.repository }}/dirinit:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        stdin: false
        tty: true
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/runtime-logs:nginx"
        volumeMounts:
          - name: filebeat-nginx-runtime-logs-volume
            mountPath: "/data/runtime-logs"
      volumes:
        - name: filebeat-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: filebeat-opensearch-curlrc-secret-volume
          secret:
            secretName: opensearch-curlrc
        - name: filebeat-certs-secret-volume
          secret:
            secretName: filebeat-certs
        - name: filebeat-zeek-volume
          persistentVolumeClaim:
            claimName: zeek-claim
        - name: filebeat-suricata-volume
          persistentVolumeClaim:
            claimName: suricata-claim
        - name: filebeat-nginx-runtime-logs-volume
          persistentVolumeClaim:
            claimName: runtime-logs-claim