---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeek-live-deployment
  namespace: malcolm
spec:
  selector:
    matchLabels:
      name: zeek-live-deployment
  replicas: 1
  template:
    metadata:
      labels:
        name: zeek-live-deployment
    spec:
      containers:
      - name: zeek-live-container
        image: ghcr.io/idaholab/malcolm/zeek:23.10.0
        imagePullPolicy: Always
        stdin: false
        tty: true
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
              - SYS_RESOURCE
        envFrom:
          - configMapRef:
              name: process-env
          - configMapRef:
              name: ssl-env
          - configMapRef:
              name: upload-common-env
          - configMapRef:
              name: zeek-env
          - secretRef:
              name: zeek-secret-env
          - configMapRef:
              name: zeek-live-env
          - configMapRef:
              name: pcap-capture-env
        env:
          - name: ZEEK_DISABLED
            value: "true"
        volumeMounts:
          - mountPath: /var/local/ca-trust/configmap
            name: zeek-live-var-local-catrust-volume
          - mountPath: "/zeek/extract_files"
            name: zeek-live-zeek-volume
            subPath: "extract_files"
          - mountPath: "/zeek/upload"
            name: zeek-live-zeek-volume
            subPath: "upload"
          - mountPath: "/opt/zeek/share/zeek/site/intel"
            name: zeek-live-zeek-intel
            subPath: "zeek/intel"
      initContainers:
      - name: zeek-live-dirinit-container
        image: ghcr.io/idaholab/malcolm/dirinit:23.10.0
        imagePullPolicy: Always
        stdin: false
        tty: true
        envFrom:
          - configMapRef:
              name: process-env
        env:
          - name: PUSER_MKDIR
            value: "/data/config:zeek/intel/MISP,zeek/intel/STIX;/data/zeek-logs:current,extract_files/preserved,extract_files/quarantine,live,processed,upload"
        volumeMounts:
          - name: zeek-live-zeek-intel
            mountPath: "/data/config"
          - name: zeek-live-zeek-volume
            mountPath: "/data/zeek-logs"
      volumes:
        - name: zeek-live-var-local-catrust-volume
          configMap:
            name: var-local-catrust
        - name: zeek-live-zeek-volume
          persistentVolumeClaim:
            claimName: zeek-claim
        - name: zeek-live-zeek-intel
          persistentVolumeClaim:
            claimName: config-claim
